### ISSUE TITLE
Use a .gitignore

### ISSUE THREAD

**Issue by mbStavola** [josh6beasttt/HikeApp#3]
You are committing your .idea folder which is useless.

Make a .gitignore to exclude it from git.

[This site](https://github.com/mrgreen3/archbang) is very handy for doing that.

**Comment by joshRamirez** [comment]
I added a gitIgnore which I hope I did correctly. The link you posted leads to the mrgreen3 archbang git repo (https://github.com/mrgreen3/archbang). Not really sure if you meant to post that one.
c9d188d
